=== Acaeris/draconika/src/assets/schema/draconika-roll-file.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": ".",
  "title": "Draconika Roll File",
  "description": "Roll table files for the Draconika DM tools.",
  "type": "object",
  "properties": {
    "version": {
      "description": "File version. Used to check for updates.",
      "type": "string"
    },
    "init": {
      "description": "Initial part to roll from the file.",
      "type": "string"
    },
    "name": {
      "description": "Display name of the file in the interface.",
      "type": "string"
    },
    "library": {
      "description": "Is this a library of tables rather than a generator to be displayed in the UI?",
      "type": "boolean"
    },
    "parts": {
      "description": "Data parts used to build the internal roll tables and generate the result.",
      "type": "object"
    }
  },
  "required": ["version", "init", "name"]
}

=== Acaeris/draconika/src/assets/tables/professions.json
{
  "init": "profession",
  "version": "0.0.3",
  "name": "Professions Library",
  "library": true,
  "parts": {
    "profession": [{
      "entries": [
        { "value": "Apprentice" },
        { "value": "Arcanist" },
        { "value": "Archdruid" },
        { "value": "Archivist" },
        { "value": "Archmage" },
        { "value": "Archmagister" },
        { "value": "Brewer" },
        { "value": "Caretaker" },
        { "value": "First Mate" },
        { "value": "Galley Chief" },
        { "value": "Huntress" },
        { "value": "Innkeeper" },
        { "value": "Lieutenant" },
        { "value": "Lorekeeper" },
        { "value": "Mariner" },
        { "value": "Pathfinder" },
        { "value": "Protector" },
        { "value": "Ranger General" },
        { "value": "Second Mate" },
        { "value": "Skycaller" },
        { "value": "Squallshaper" },
        { "value": "Tracker" },
        { "value": "Valewalker" },
        { "value": "Warden" },
        { "value": "Wildwatcher" }
      ]
    }, {
      "restrictions": {
        "gender": [ "male" ]
      },
      "entries": [
        { "value": "Father" },
        { "value": "Priest" },
        { "value": "Prince" }
      ]
    }, {
      "restrictions": {
        "gender": [ "female" ]
      },
      "entries": [
        { "value": "Mother" },
        { "value": "Priestess" },
        { "value": "Princess" },
        { "value": "Sentinel" }
      ]
    }]
  }
}

=== Acaeris/draconika/src/assets/tables/race.json
{
  "$schema": "../schema/draconika-roll-file.json",
  "init": "race",
  "name": "Race Generator",
  "version": "0.1.0",
  "parts": {
    "race": [{
      "restrictions": {
        "setting": [ "azeroth" ],
        "faction": [ "alliance" ],
        "types": [ "humanoid" ]
      },
      "entries": [
        { "value": "Stormwind Human" },
        { "value": "Kul'tiran Human" },
        { "value": "Gilnean Human" },
        { "value": "High Elf" },
        { "value": "Night Elf" },
        { "value": "Void Elf" },
        { "value": "Exodar Draenei" },
        { "value": "Lightforged Draenei" },
        { "value": "Gnome" },
        { "value": "Ironforge Dwarf" },
        { "value": "Dark Iron Dwarf" },
        { "value": "Wildhammer Dwarf" }
      ]
    }, {
      "restrictions": {
        "setting": [ "azeroth" ],
        "faction": [ "horde" ],
        "types": [ "humanoid" ]
      },
      "entries": [
        { "value": "Blood Elf" },
        { "value": "Nightborne" },
        { "value": "Forsaken" },
        { "value": "Thunderbluff Taruen" },
        { "value": "Highmountain Tauren" },
        { "value": "Orc" },
        { "value": "Mag'har Orc" },
        { "value": "Darkspear Troll" },
        { "value": "Zandalari Troll" },
        { "value": "Goblin" }
      ]
    }, {
      "restrictions": {
        "setting": [ "azeroth" ],
        "faction": [ "horde", "alliance" ],
        "types": [ "humanoid" ]
      },
      "entries": [
        { "value": "Pandaren" }
      ]
    }, {
      "restrictions": {
        "setting": [ "azeroth" ],
        "types": [ "wild" ]
      },
      "entries": [
        { "value": "Mechagnome" },
        { "value": "Amani Troll" },
        { "value": "Gurubashi Troll" },
        { "value": "Naga" },
        { "value": "Vulpera" },
        { "value": "Furbolg" },
        { "value": "Owlkin" },
        { "value": "Ogre" }
      ]
    }, {
      "restrictions": {
        "setting": [ "azeroth" ],
        "types": [ "corrupted" ],
        "faction": [ "legion" ]
      },
      "entries": [
        { "value": "Sayaadi" },
        { "value": "Nathrezim" },
        { "value": "Shivarra" },
        { "value": "Eredar" }
      ]
    }, {
      "restrictions": {
        "setting": [ "forgotten realms"],
        "types": [ "humanoid" ]
      },
      "entries": [
        { "value": "Human", "chance": 10 },
        { "value": "High Elf", "chance": 5 },
        { "value": "Wood Elf", "chance": 5 },
        { "value": "Eladrin Elf" },
        { "value": "Hill Dwarf" , "chance": 4 },
        { "value": "Mountain Dwarf", "chance": 5 },
        { "value": "Stout Halfling", "chance": 5 },
        { "value": "Lightfoot Halfling", "chance": 5 },
        { "value": "Ghostwise Halfling" },
        { "value": "Forest Gnome", "chance": 2 },
        { "value": "Rock Gnome", "chance": 2 },
        { "value": "Deep Gnome" },
        { "value": "Half-orc", "chance": 3 },
        { "value": "Half-elf", "chance": 4 },
        { "value": "Dragonborn", "chance": 4 },
        { "value": "Infernal Tiefling", "chance": 2 },
        { "value": "Feral Tiefling", "chance": 2 },
        { "value": "Protector Aasimar", "chance": 2 },
        { "value": "Scourge Aasimar" },
        { "value": "Fallen Aasimar" },
        { "value": "Aarakocra", "chance": 3 },
        { "value": "Goliath", "chance": 4 },
        { "value": "Air Genasi" },
        { "value": "Earth Genasi" },
        { "value": "Fire Genasi" },
        { "value": "Water Genasi" },
        { "value": "Tabaxi", "chance": 3 },
        { "value": "Firbolg", "chance": 3 },
        { "value": "Triton", "chance": 3 },
        { "value": "Kenku", "chance": 3 },
        { "value": "Lizardfolk", "chance": 4 },
        { "value": "Duergar Dwarf" },
        { "value": "Drow" },
        { "value": "Kobold" },
        { "value": "Orc" },
        { "value": "Hobgoblin" },
        { "value": "Goblin" },
        { "value": "Bugbear" },
        { "value": "Yuan-Ti Pureblood" }
      ]
    }]
  }
}

=== Acaeris/draconika/src/assets/tables/test.json
{
  "init": "test",
  "version": "0.0.1",
  "name": "Feature tests",
  "parts": {
    "test": [{
      "restrictions": {
        "test": [ "dice" ]
      },
      "entries": [
        { "value": "[#1d6] 1d6" },
        { "value": "[#2d6] 2d6" },
        { "value": "[#1d20] 1d20" }
      ]
    }]
  }
}

=== Acaeris/draconika/src/assets/tables/gnome-name.json
{
  "init": "format",
  "version": "1.0.1",
  "name": "D&D Gnome Name Library",
  "library": true,
  "parts": {
    "format": [{
      "restrictions": {
        "race": [ "gnome" ]
      },
      "entries": [
        { "value": "[firstName] [lastName]" }
      ]
    }],
    "firstName": [{
      "restrictions": {
        "gender": [ "female" ],
        "race": [ "gnome" ]
      },
      "entries": [
        { "value": "Abalaba" },
        { "value": "Bimpnottin" },
        { "value": "Breena" },
        { "value": "Buvvie" },
        { "value": "Callybon" },
        { "value": "Caramip" },
        { "value": "Carlin" },
        { "value": "Cumpen" },
        { "value": "Dalaba" },
        { "value": "Donella" },
        { "value": "Duvamil" },
        { "value": "Ella" },
        { "value": "Ellyjoybell" },
        { "value": "Ellywick" },
        { "value": "Enidda" },
        { "value": "Lilli" },
        { "value": "Loopmottin" },
        { "value": "Lorilla" },
        { "value": "Luthra" },
        { "value": "Mardnab" },
        { "value": "Meena" },
        { "value": "Menny" },
        { "value": "Mumpena" },
        { "value": "Nissa" },
        { "value": "Numba" },
        { "value": "Nyx" },
        { "value": "Oda" },
        { "value": "Oppah" },
        { "value": "Orla" },
        { "value": "Panana" },
        { "value": "Pyntle" },
        { "value": "Quilla" },
        { "value": "Ranala" },
        { "value": "Reddlepop" },
        { "value": "Roywyn" },
        { "value": "Salanop" },
        { "value": "Shamil" },
        { "value": "Siffress" },
        { "value": "Symma" },
        { "value": "Tana" },
        { "value": "Tenena" },
        { "value": "Tervaround" },
        { "value": "Tippletoe" },
        { "value": "Ulla" },
        { "value": "Unvera" },
        { "value": "Veloptima" },
        { "value": "Virra" },
        { "value": "Waywocket" },
        { "value": "Yebe" },
        { "value": "Zanna" }
      ]
    }, {
      "restrictions": {
        "gender": [ "male" ],
        "race": [ "gnome" ]
      },
      "entries": [
        { "value": "Alston" },
        { "value": "Alvyn" },
        { "value": "Anverth" },
        { "value": "Arumawann" },
        { "value": "Bilbron" },
        { "value": "Boddybock" },
        { "value": "Brocc" },
        { "value": "Burgell" },
        { "value": "Cockaby" },
        { "value": "Crampernap" },
        { "value": "Dabbledob" },
        { "value": "Delebean" },
        { "value": "Dimble" },
        { "value": "Eberdeb" },
        { "value": "Eldon" },
        { "value": "Erky" },
        { "value": "Fablen" },
        { "value": "Fibblestib" },
        { "value": "Fonkin" },
        { "value": "Frouse" },
        { "value": "Frug" },
        { "value": "Gerbo" },
        { "value": "Gimble" },
        { "value": "Glim" },
        { "value": "Igden" },
        { "value": "Jabble" },
        { "value": "Jebeddo" },
        { "value": "Kellen" },
        { "value": "Kipper" },
        { "value": "Namfoodle" },
        { "value": "Oppleby" },
        { "value": "Orryn" },
        { "value": "Paggen" },
        { "value": "Pallabar" },
        { "value": "Pog" },
        { "value": "Qualen" },
        { "value": "Ribbles" },
        { "value": "Rimple" },
        { "value": "Roondar" },
        { "value": "Sapply" },
        { "value": "Seebo" },
        { "value": "Senteq" },
        { "value": "Sindri" },
        { "value": "Umpen" },
        { "value": "Warryn" },
        { "value": "Wiggens" },
        { "value": "Wobbles" },
        { "value": "Wrenn" },
        { "value": "Zaffrab" },
        { "value": "Zook" }
      ]
    }],
    "lastName": [{
      "restrictions": {
        "race": [ "gnome" ]
      },
      "entries": [
        { "value": "Albaratie" },
        { "value": "Bafflestone" },
        { "value": "Beren" },
        { "value": "Boondiggles" },
        { "value": "Cobblelob" },
        { "value": "Daergel" },
        { "value": "Dunben" },
        { "value": "Fabblestabble" },
        { "value": "Fapplestamp" },
        { "value": "Fiddlefen" },
        { "value": "Folkor" },
        { "value": "Garrick" },
        { "value": "Gimlen" },
        { "value": "Glittergem" },
        { "value": "Gobblefirn" },
        { "value": "Gummen" },
        { "value": "Horcusporcus" },
        { "value": "Humplebumple" },
        { "value": "Ironhide" },
        { "value": "Leffery" },
        { "value": "Lingenhall" },
        { "value": "Loofollue" },
        { "value": "Maekkelferce" },
        { "value": "Miggledy" },
        { "value": "Munggen" },
        { "value": "Murnig" },
        { "value": "Musgraben" },
        { "value": "Nackle" },
        { "value": "Ningel" },
        { "value": "Nopenstallen" },
        { "value": "Nucklestamp" },
        { "value": "Offund" },
        { "value": "Oomtrowl" },
        { "value": "Pilwicken" },
        { "value": "Pingun" },
        { "value": "Quillsharpener" },
        { "value": "Raulner" },
        { "value": "Reese" },
        { "value": "Rofferton" },
        { "value": "Scheppen" },
        { "value": "Shadowcloak" },
        { "value": "Silverthread" },
        { "value": "Sympony" },
        { "value": "Tarkelby" },
        { "value": "Timbers" },
        { "value": "Turen" },
        { "value": "Umbodoben" },
        { "value": "Waggletop" },
        { "value": "Welber" },
        { "value": "Wildwander" }
      ]
    }]
  }
}

=== Acaeris/draconika/src/assets/tables/eldrich-forest-monsters.json
{
  "init": "monsters",
  "version": "0.0.1",
  "name": "Eldrich Forest Encounter Generator",
  "parts": {
    "monsters": [{
      "entries": [
        { "value": "1 psuedodragon", "chance": 5 },
        { "value": "1 werewolf", "chance": 4 },
        { "value": "1 yellow musk creeper", "chance": 3 },
        { "value": "1 assassin vine", "chance": 5 },
        { "value": "1 ettercap", "chance": 4 },
        { "value": "1 giant mantis", "chance": 3 },
        { "value": "1 owlbear", "chance": 7 },
        { "value": "1 hydra", "chance": 3 },
        { "value": "[#1d4] worgs", "chance": 5 },
        { "value": "1 basilisk", "chance": 6 },
        { "value": "[#1d4] dryads", "chance": 6 },
        { "value": "[#1d4] unicorns", "chance": 5 },
        { "value": "[#1d6] centaurs", "chance": 3 },
        { "value": "1 girallon", "chance": 2 },
        { "value": "[#1d4] half celestial unicorns", "chance": 6 },
        { "value": "[#1d4] satyrs", "chance": 3 },
        { "value": "1 shambling mound", "chance": 3 },
        { "value": "1 dire bear", "chance": 2 },
        { "value": "1 nymph", "chance": 6 },
        { "value": "[#2d4] pegasi", "chance": 4 },
        { "value": "[#1d6] pixies", "chance": 5 },
        { "value": "1 treant", "chance": 5 },
        { "value": "1 gorgon", "chance": 4 },
        { "value": "1 couatl", "chance": 2 }
      ]
    }]
  }
}

=== Acaeris/draconika/src/assets/tables/encounters.json
{
  "init": "encounters",
  "version": "1.0.1",
  "name": "Encounters generator",
  "parts": {
    "encounters": [{
      "restrictions": {
        "location": [ "city" ]
      },
      "entries": [
        { "value": "A fire rages across the city, destroying major portions of it." },
        { "value": "Worg attacks pepper the town over several days." },
        { "value": "Witness a murder." },
        { "value": "Alchemical explosion happens in a nearby building." },
        { "value": "Major disease outbreak." },
        { "value": "Roving gangs intimidate and extort citizens." },
        { "value": "A noble suddenly dies, his funeral draws sadness, or celebration." },
        { "value": "Kids start disappearing." },
        { "value": "Party find a corpse." },
        { "value": "A curfew is enacted." },
        { "value": "Poison mold outbreak." },
        { "value": "Gladiator battles are held." },
        { "value": "A revenant stalks its prey but isn't harming anyone else." },
        { "value": "Shadow infestation." },
        { "value": "Druids begin protesting the city's expansion." },
        { "value": "A naked person in chains is marched through the street." },
        { "value": "You find a purse full of coins." },
        { "value": "You hear someone following you, but they vanish." },
        { "value": "Wrestling tournament is being held." },
        { "value": "Two wizards get into an eye for an eye war that is hurting the town." },
        { "value": "A cleric tries to convert the party." },
        { "value": "Poison gas comes up from the sewer (or well)." },
        { "value": "Wererats!" },
        { "value": "A parade blocks off part of the town." },
        { "value": "A cart of dead bodies is driven by." },
        { "value": "Party member inadvertently harms an innocent." },
        { "value": "A noble holds an emergency address." },
        { "value": "Two bar patrons' argument escalates to weapons." },
        { "value": "Martial law is declared." },
        { "value": "Someone tries to sell you a slave." },
        { "value": "Witness a petty theft." },
        { "value": "A major church abruptly closes its doors." },
        { "value": "Hungry child asks for help." },
        { "value": "Town leadership locks city down." },
        { "value": "Child fell into a well (or trapped under something heavy)." },
        { "value": "Party member or members get food poisoning." },
        { "value": "A public execution is held." },
        { "value": "You find a vendor who appears to not know he's selling a magic item." },
        { "value": "Tax collectors start demanding exorbitant fees." },
        { "value": "A yound adventurer starts following the players." },
        { "value": "A business has loud obnoxious sounds coming from it all night." },
        { "value": "Somone has been robbing graves." },
        { "value": "A merchant is selling tinctures and is making a killing at it." },
        { "value": "A particularly aggressive beggar harasses the party." },
        { "value": "Pickpocket.", "chance": 11 },
        { "value": "An annoyingly persistant salesman eyes the party." },
        { "value": "Party stumbles across an innocent being beaten." },
        { "value": "A heavy storm comes down." },
        { "value": "Farm animal or animals run amok." },
        { "value": "A citizen lights themselves on fire." },
        { "value": "Party member get sadled with a curse." },
        { "value": "Naked drunk runs through the streets chased by a guard." },
        { "value": "A physical altercation turns into a duel in a crowded street." },
        { "value": "Prostitute tries to turn tricks from the party." },
        { "value": "Rats swarm the streets." },
        { "value": "Two people both claim ownership of a valuable item." },
        { "value": "Street con man tries to bait players into betting on a rigged game." },
        { "value": "Player gets splashed with a foul smelling liquid that won't wash off." },
        { "value": "A sinkhole forms." },
        { "value": "A lynch mob gathers to kill a `witch` who lives outside of town." },
        { "value": "A troupe starts a street performance." },
        { "value": "Street thug picks a fight." },
        { "value": "A citizen tries to charm a player." },
        { "value": "Citizen accuses a player of adultery with their partner." },
        { "value": "Town guard bring party member in for trial." },
        { "value": "Vandals tear through town." },
        { "value": "Prophet claims a major disaster is imminent." },
        { "value": "A bard is playing songs that put people to sleep." },
        { "value": "Freak storm buries the town in 5 foot of snow." },
        { "value": "A solar or lunar eclipse occurs." },
        { "value": "A dragon flies over town." },
        { "value": "Young adventurer starts showing off recently acquired treasure." },
        { "value": "Party finds an important looking key." },
        { "value": "A street dog attacks you." },
        { "value": "Famine." },
        { "value": "You find a letter with a royal signet." },
        { "value": "Citizens are being polymorphed." },
        { "value": "City floods." },
        { "value": "A full on riot breaks out." },
        { "value": "A succubus or incubus seduces a player." },
        { "value": "A player gets captured by mystery cult." },
        { "value": "A citizen breaks an item of a player accidentally." },
        { "value": "A cult becomes popular and recruits denizens." },
        { "value": "Your favourite vendor doesn't open up shop one day. Whereabouts are unknown." },
        { "value": "A werewolf is on the loose." },
        { "value": "A serial killer stalks the night." },
        { "value": "A paladin starts accusing people of witchcraft." },
        { "value": "A golem roams the street with no master." },
        { "value": "The town well is poisoned." },
        { "value": "Party gets invited to an important noble's home." }
      ]
    }]
  }
}

=== Acaeris/draconika/src/assets/tables/npc-mannerisms.json
{
  "init": "mannerisms",
  "version": "1.0.0",
  "name": "NPC Mannerisms",
  "parts": {
    "mannerisms": [{
      "entries": [
        { "value": "Prone to singing, whistling or humming quietly" },
        { "value": "Speaks in rhyme or some other peculiar way"},
        { "value": "Particularly low or high voice" },
        { "value": "Slurs words, lisps or stutters" },
        { "value": "Enunciates overly clearly" },
        { "value": "Speaks loudly" },
        { "value": "Whispers" },
        { "value": "Uses flowery speech or long words" },
        { "value": "Makes constant jokes or puns" },
        { "value": "Prone to predictions of doom" },
        { "value": "Fidgets" },
        { "value": "Squints" },
        { "value": "Stares into the distance" },
        { "value": "Chews something" },
        { "value": "Paces" },
        { "value": "Taps fingers" },
        { "value": "Bites fingernails" },
        { "value": "Twirls hair or tugs beard" }
      ]
    }]
  }
}

=== Acaeris/draconika/src/assets/tables/dwarf-name.json
{
  "init": "format",
  "version": "1.0.0",
  "name": "D&D Dwarf Name Library",
  "library": true,
  "parts": {
    "format": [{
      "restrictions": {
        "race": [ "dwarf" ]
      },
      "entries": [
        { "value": "[firstName] of Clan [lastName]", "chance": 20 }
      ]
    }],
    "firstName": [{
      "restrictions": {
        "gender": [ "female" ],
        "race": [ "dwarf" ]
      },
      "entries": [
        { "value": "Anbera" },
        { "value": "Artin" },
        { "value": "Audhild" },
        { "value": "Balifra" },
        { "value": "Barbena" },
        { "value": "Bardryn" },
        { "value": "Bolhild" },
        { "value": "Dagnal" },
        { "value": "Dariff" },
        { "value": "Delre" },
        { "value": "Diesa" },
        { "value": "Eldeth" },
        { "value": "Eridred" },
        { "value": "Falkrunn" },
        { "value": "Fallthra" },
        { "value": "Finellen" },
        { "value": "Gillydd" },
        { "value": "Gunnloda" },
        { "value": "Gurdis" },
        { "value": "Helgret" },
        { "value": "Helja" },
        { "value": "Hlin" },
        { "value": "Ilde" },
        { "value": "Jarana" },
        { "value": "Kathra" },
        { "value": "Kilia" },
        { "value": "Kristryd" },
        { "value": "Liftrasa" },
        { "value": "Marastyr" },
        { "value": "Mardred" },
        { "value": "Morana" },
        { "value": "Nalaed" },
        { "value": "Nora" },
        { "value": "Nurkara" },
        { "value": "Oriff" },
        { "value": "Ovina" },
        { "value": "Riswynn" },
        { "value": "Sannl" },
        { "value": "Therlin" },
        { "value": "Thodris" },
        { "value": "Torbera" },
        { "value": "Tordrid" },
        { "value": "Torgga" },
        { "value": "Urshar" },
        { "value": "Valida" },
        { "value": "Vistra" },
        { "value": "Vonana" },
        { "value": "Werydd" },
        { "value": "Whurdred" },
        { "value": "Yurgunn" }
      ]
    }, {
      "restrictions": {
        "gender": [ "male" ],
        "race": [ "dwarf" ]
      },
      "entries": [
        { "value": "Adrik" },
        { "value": "Alberich" },
        { "value": "Baern" },
        { "value": "Barendd" },
        { "value": "Beloril" },
        { "value": "Brottor" },
        { "value": "Dain" },
        { "value": "Dalgal" },
        { "value": "Darrak" },
        { "value": "Delg" },
        { "value": "Duergath" },
        { "value": "Dworic" },
        { "value": "Eberk" },
        { "value": "Einkil" },
        { "value": "Elaim" },
        { "value": "Erias" },
        { "value": "Fallond" },
        { "value": "Fargrim" },
        { "value": "Gardain" },
        { "value": "Gilthur" },
        { "value": "Gimgen" },
        { "value": "Gimurt" },
        { "value": "Harbek" },
        { "value": "Kildrak" },
        { "value": "Kilvar" },
        { "value": "Morgran" },
        { "value": "Morkral" },
        { "value": "Nalral" },
        { "value": "Nordak" },
        { "value": "Nuraval" },
        { "value": "Oloric" },
        { "value": "Olunt" },
        { "value": "Orsik" },
        { "value": "Oskar" },
        { "value": "Rangrim" },
        { "value": "Reirak" },
        { "value": "Rurik" },
        { "value": "Taklinn" },
        { "value": "Thoradin" },
        { "value": "Thorin" },
        { "value": "Thradal" },
        { "value": "Tordek" },
        { "value": "Traubon" },
        { "value": "Travok" },
        { "value": "Ulfgar" },
        { "value": "Uraim" },
        { "value": "Veit" },
        { "value": "Vonbin" },
        { "value": "Vondal" },
        { "value": "Whurbin" }
      ]
    }],
    "lastName": [{
      "restrictions": {
        "race": [ "dwarf" ]
      },
      "entries": [
        { "value": "Aranore" },
        { "value": "Balderk" },
        { "value": "Battlehammer" },
        { "value": "Bigtoe" },
        { "value": "Bloodkith" },
        { "value": "Bofdann" },
        { "value": "Brawnanvil" },
        { "value": "Brazzik" },
        { "value": "Broodfist" },
        { "value": "Burrowfound" },
        { "value": "Caebrek" },
        { "value": "Daerdahk" },
        { "value": "Dankil" },
        { "value": "Daraln" },
        { "value": "Deepdelver" },
        { "value": "Durthane" },
        { "value": "Eversharp" },
        { "value": "Fallack" },
        { "value": "Fireforge" },
        { "value": "Foamtankard" },
        { "value": "Frostbeard" },
        { "value": "Glanhig" },
        { "value": "Goblinbane" },
        { "value": "Goldfinder" },
        { "value": "Gorunn" },
        { "value": "Graybeard" },
        { "value": "Hammerstone" },
        { "value": "Helcral" },
        { "value": "Holderhek" },
        { "value": "Ironfist" },
        { "value": "Loderr" },
        { "value": "Lutgehr" },
        { "value": "Morigak" },
        { "value": "Orcfoe" },
        { "value": "Rakankrak" },
        { "value": "Ruby-Eye" },
        { "value": "Rumnaheim" },
        { "value": "Silveraxe" },
        { "value": "Silverstone" },
        { "value": "Steelfist" },
        { "value": "Stoutale" },
        { "value": "Strakeln" },
        { "value": "Strongheart" },
        { "value": "Thrahak" },
        { "value": "Torevir" },
        { "value": "Torunn" },
        { "value": "Trollbleeder" },
        { "value": "Trueanvil" },
        { "value": "Trueblood" },
        { "value": "Ungart" }
      ]
    }]
  }
}
