=== Acaeris/draconika/src/assets/schema/draconika-roll-file.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": ".",
  "title": "Draconika Roll File",
  "description": "Roll table files for the Draconika DM tools.",
  "type": "object",
  "properties": {
    "version": {
      "description": "File version. Used to check for updates.",
      "type": "string"
    },
    "init": {
      "description": "Initial part to roll from the file.",
      "type": "string"
    },
    "name": {
      "description": "Display name of the file in the interface.",
      "type": "string"
    },
    "library": {
      "description": "Is this a library of tables rather than a generator to be displayed in the UI?",
      "type": "boolean"
    },
    "parts": {
      "description": "Data parts used to build the internal roll tables and generate the result.",
      "type": "object"
    }
  },
  "required": ["version", "init", "name"]
}

=== Acaeris/draconika/src/assets/tables/npc-talents.json
{
  "init": "talents",
  "version": "1.0.0",
  "name": "NPC Talents",
  "parts": {
    "talents": [{
      "entries": [
        { "value": "Plays a musical instrument" },
        { "value": "Speaks several languages fluently" },
        { "value": "Unbelievably lucky" },
        { "value": "Perfect memory" },
        { "value": "Great with animals" },
        { "value": "Great with children" },
        { "value": "Great at solving puzzles" },
        { "value": "Great at one game" },
        { "value": "Great at impersonations" },
        { "value": "Draws beautifully" },
        { "value": "Paints beautifully" },
        { "value": "Sings beautifully" },
        { "value": "Drinks everyone under the table" },
        { "value": "Expert carpenter" },
        { "value": "Expert cook" },
        { "value": "Expert dart thrower and rock skipper" },
        { "value": "Expert juggler" },
        { "value": "Skilled actor and master of disguise" },
        { "value": "Skilled dancer" },
        { "value": "Knows thieves' cant" }
      ]
    }]
  }
}

=== Acaeris/draconika/src/assets/tables/elf-name.json
{
  "init": "format",
  "version": "0.2.1",
  "name": "D&D Elf Name Library",
  "library": true,
  "parts": {
    "format": [{
      "restrictions": {
        "race": [ "elf" ]
      },
      "entries": [
        { "value": "[elf-name.childName] [lastName]"},
        { "value": "[firstName] [lastName]" }
      ]
    }],
    "firstName": [{
      "restrictions": {
        "age": [ "child" ],
        "race": [ "elf" ]
      },
      "entries": [

      ]
     }, {
      "restrictions": {
        "age": [ "adult" ],
        "gender": [ "female" ],
        "race": [ "elf" ]
      },
      "entries": [

      ]
    }, {
      "restrictions": {
        "age": [ "adult" ],
        "gender": [ "male" ],
        "race": [ "elf" ]
      },
      "entries": [
        { "value": "Adran" },
        { "value": "Aelar" },
        { "value": "Aerdeth" },
        { "value": "Ahvain" },
        { "value": "Aramil" },
        { "value": "Arannis" },
        { "value": "Aust" },
        { "value": "Azaki" },
        { "value": "Beiro" },
        { "value": "Berrian" },
        { "value": "Caeldrim" },
        { "value": "Carric" },
        { "value": "Dayereth" },
        { "value": "Dreali" },
        { "value": "Efferil" },
        { "value": "Eiravel" },
        { "value": "Enialis" },
        { "value": "Erdan" },
        { "value": "Erevan" },
        { "value": "Fivin" },
        { "value": "Galinndan" },
        { "value": "Gennal" },
        { "value": "Hadarai" },
        { "value": "Halimath" },
        { "value": "Heian" },
        { "value": "Himo" },
        { "value": "Immeral" },
        { "value": "Ivellios" },
        { "value": "Korfel" },
        { "value": "Lamlis" },
        { "value": "Laucian" },
        { "value": "Lucan" },
        { "value": "Mindartis" },
        { "value": "Naal" },
        { "value": "Nutae" },
        { "value": "Paelias" },
        { "value": "Peren" },
        { "value": "Quarion" },
        { "value": "Riardon" },
        { "value": "Rolen" },
        { "value": "Soveliss" },
        { "value": "Suhnae" },
        { "value": "Thamior" },
        { "value": "Tharivol" },
        { "value": "Theren" },
        { "value": "Theriatis" },
        { "value": "Thervan" },
        { "value": "Uthemar" },
        { "value": "Vanuath" },
        { "value": "Varis" }
      ]
    }],
    "lastName": [{
      "restrictions": {
        "race": [ "elf" ]
      },
      "entries": [
        { "value": "Aloro" },
        { "value": "Amakiir" },
        { "value": "Amastacia" },
        { "value": "Ariessus" },
        { "value": "Arnuanna" },
        { "value": "Berevan" },
        { "value": "Caerdonel" },
        { "value": "Caphaxath" },
        { "value": "Casilltenirra" },
        { "value": "Cithreth" },
        { "value": "Dalanthan" },
        { "value": "Eathalena" },
        { "value": "Erenaeth" },
        { "value": "Ethanasath" },
        { "value": "Fasharash" },
        { "value": "Firahel" },
        { "value": "Floshem" },
        { "value": "Galanodel" },
        { "value": "Goltorah" },
        { "value": "Hanali" },
        { "value": "Holimion" },
        { "value": "Horineth" },
        { "value": "Iathrana" },
        { "value": "Ilphelkiir" },
        { "value": "Iranapha" },
        { "value": "Koehlanna" },
        { "value": "Lathalas" },
        { "value": "Liadon" },
        { "value": "Meliamne" },
        { "value": "Mellerelel" },
        { "value": "Mystralah" },
        { "value": "Nailo" },
        { "value": "Netyoive" },
        { "value": "Ofandrus" },
        { "value": "Ostoroth" },
        { "value": "Othronus" },
        { "value": "Qualanthri" },
        { "value": "Raethran" },
        { "value": "Rothenel" },
        { "value": "Selevarun" },
        { "value": "Siannodel" },
        { "value": "Suitrasas" },
        { "value": "Sylvaranth" },
        { "value": "Teinithra" },
        { "value": "Tiltahana" },
        { "value": "Wasanthi" },
        { "value": "Withrethin" },
        { "value": "Xiloscient" },
        { "value": "Xistsrith" },
        { "value": "Yaeldrin" }
      ]
    }]
  }
}

=== Acaeris/draconika/src/assets/tables/material.json
{
  "init": "base",
  "version": "1.0.2",
  "name": "Material library",
  "library": true,
  "parts": {
    "base": [{
      "entries": [
        { "value": "wood" },
        { "value": "gold" },
        { "value": "silver" },
        { "value": "bronze" },
        { "value": "copper" },
        { "value": "steel" },
        { "value": "iron" },
        { "value": "mithril" },
        { "value": "tin" },
        { "value": "adamantine" },
        { "value": "an unknown material" },
        { "value": "brass" }
      ]
    }]
  }
}

=== Acaeris/draconika/src/assets/tables/weather.json
{
  "$schema": "../schema/draconika-roll-file.json",
  "init": "weather",
  "version": "0.0.1",
  "name": "Weather generator",
  "parts": {
    "weather": [{
      "entries": [
        { "value": "Temperature: [temperature] - Wind: [wind] - Precipitation: [precipitation]" }
      ]
    }],
    "temperature": [{
      "entries": [
        { "value": "Normal for the season", "chance": 14 },
        { "value": "[#1d40] &deg;F colder than normal", "chance": 3 },
        { "value": "[#1d40] &deg;F hotter than normal", "chance": 3 }
      ]
    }],
    "wind": [{
      "entries": [
        { "value": "None", "chance": 12 },
        { "value": "Light", "chance": 5 },
        { "value": "Strong", "chance": 3 }
      ]
    }],
    "precipitation": [{
      "entries": [
        { "value": "None", "chance": 12 },
        { "value": "Light rain or light snowfall", "chance": 5 },
        { "value": "Heavy rain or heavy snowfall", "chance": 3 }
      ]
    }]
  }
}

=== Acaeris/draconika/src/assets/tables/human-name.json
{
  "init": "format",
  "version": "0.0.4",
  "name": "Human Name Library",
  "library": true,
  "parts": {
    "format":  [{
      "restrictions": {
        "race": [ "human" ]
      },
      "entries": [
        { "value": "[title] [firstName] [lastName]-[lastName]" },
        { "value": "[firstName] [lastName]-[lastName]" },
        { "value": "[profession] [lastName]-[lastName]" },
        { "value": "[profession] [lastName]-[lastName] "}
      ]
    }],
    "firstName": [{
      "restrictions": {
        "gender": [ "male" ],
        "race": [ "human" ],
        "language": [ "english" ]
      },
      "entries": [
        { "value": "Adam" },
        { "value": "Alan" },
        { "value": "Connor" },
        { "value": "Daniel" },
        { "value": "Douglas" },
        { "value": "Dwayne" },
        { "value": "Edward" },
        { "value": "Elliot" },
        { "value": "Eston" },
        { "value": "Gabe" },
        { "value": "Gabriel" },
        { "value": "Gordon" },
        { "value": "Greg" },
        { "value": "Gregory" },
        { "value": "Jacob" },
        { "value": "Jeremy" },
        { "value": "Joe" },
        { "value": "John" },
        { "value": "Joseph" },
        { "value": "Ken" },
        { "value": "Kevin" },
        { "value": "Mark" },
        { "value": "Martin" },
        { "value": "Matt" },
        { "value": "Matthew" },
        { "value": "Michael" },
        { "value": "Nathan" },
        { "value": "Nathaniel" },
        { "value": "Pete" },
        { "value": "Peter" },
        { "value": "Sammy" },
        { "value": "Samuel" },
        { "value": "Tim" },
        { "value": "Timothy" },
        { "value": "Tom" },
        { "value": "Warren" },
        { "value": "Winston" }
      ]
    }, {
      "restrictions": {
        "gender": [ "male" ],
        "race": [ "human" ],
        "language": [ "swedish" ]
      },
      "entries": [
        { "value": "Torbjorn" }
      ]
    }, {
      "restrictions": {
        "gender": [ "male" ],
        "race": [ "human" ],
        "language": [ "spanish" ]
      },
      "entries": [
        { "value": "Alexandre" },
        { "value": "Alfonso" },
        { "value": "Alonso" },
        { "value": "Anthon" },
        { "value": "Arcos" },
        { "value": "Arnaut" },
        { "value": "Arturo" },
        { "value": "Bartoleme" },
        { "value": "Benito" },
        { "value": "Bernat" },
        { "value": "Blasco" },
        { "value": "Carlos" },
        { "value": "Damian" },
        { "value": "Diego" },
        { "value": "Domingo" },
        { "value": "Enrique" },
        { "value": "Escobar" },
        { "value": "Ettor" },
        { "value": "Fernando" },
        { "value": "Francisco" },
        { "value": "Gabriel" },
        { "value": "Garcia" },
        { "value": "Gaspar" },
        { "value": "Gil" },
        { "value": "Gomes" },
        { "value": "Goncalo" },
        { "value": "Gostantin" },
        { "value": "Jayme" },
        { "value": "Joan" },
        { "value": "Jorge" },
        { "value": "Jose" },
        { "value": "Juan" },
        { "value": "Machin" },
        { "value": "Martin" },
        { "value": "Mateu" },
        { "value": "Miguel" },
        { "value": "Nicolas" },
        { "value": "Pascual" },
        { "value": "Pedro" },
        { "value": "Porico" },
        { "value": "Ramiro" },
        { "value": "Ramon" },
        { "value": "Rodrigo" },
        { "value": "Sabastian" },
        { "value": "Salvador" },
        { "value": "Simon" },
        { "value": "Tomas" },
        { "value": "Tristan" },
        { "value": "Valeriano" },
        { "value": "Ynigo" }
      ]
    }, {
      "restrictions": {
        "gender": [ "female" ],
        "race": [ "human" ],
        "language": [ "english" ]
      },
      "entries": [
        { "value": "Amy" },
        { "value": "Angela" },
        { "value": "Anna" },
        { "value": "Annabelle" },
        { "value": "Annie" },
        { "value": "Astrid" },
        { "value": "Brigitte" },
        { "value": "Caitlyn" },
        { "value": "Eleanor" },
        { "value": "Elly" },
        { "value": "Elspeth" },
        { "value": "Hanna" },
        { "value": "Hannah" },
        { "value": "Jane" },
        { "value": "Janet" },
        { "value": "Jen" },
        { "value": "Jennifer" },
        { "value": "Kate" },
        { "value": "Katie" },
        { "value": "Lana" },
        { "value": "Laura" },
        { "value": "Lily" },
        { "value": "Lisa" },
        { "value": "Natalie" },
        { "value": "Pam" },
        { "value": "Pamela" },
        { "value": "Vera" }
      ]
    }, {
      "restrictions": {
        "race": [ "human" ]
      },
      "entries": [
        { "value": "Sam" },
        { "value": "Terry" }
      ]
    }],
    "lastName": [{
      "restrictions": {
        "race": [ "human" ]
      },
      "entries": [
        { "value": "Addams" },
        { "value": "Churchill" },
        { "value": "Cunningham" },
        { "value": "Edwards" },
        { "value": "Glasman" },
        { "value": "Gregory" },
        { "value": "Hodgins" },
        { "value": "Hodgkins" },
        { "value": "Hunt" },
        { "value": "Jackson" },
        { "value": "Johnson" },
        { "value": "Kidman" },
        { "value": "Lindholm" },
        { "value": "McCoy" },
        { "value": "McHugh" },
        { "value": "Newman" },
        { "value": "Osborne" },
        { "value": "Portman" },
        { "value": "Reyes" },
        { "value": "Smith" },
        { "value": "Stewart" },
        { "value": "Tompkins" },
        { "value": "Wells" },
        { "value": "Western" }
      ]
    }]
  }
}

=== Acaeris/draconika/src/assets/tables/dragonborn-name.json
{
  "init": "format",
  "version": "1.0.0",
  "name": "Dragonborn Name Library",
  "library": true,
  "parts": {
    "format": [{
      "restrictions": {
        "race": [ "dragonborn" ]
      },
      "entries": [
        { "value": "[firstName] of Clan [lastName]", "chance": 20 }
      ]
    }],
    "firstName": [{
      "restrictions": {
        "gender": [ "female" ],
        "race": [ "dragonborn" ]
      },
      "entries": [
        { "value": "Akra" },
        { "value": "Aasathra" },
        { "value": "Antara" },
        { "value": "Arava" },
        { "value": "Biri" },
        { "value": "Blendaeth" },
        { "value": "Burana" },
        { "value": "Chassath" },
        { "value": "Daar" },
        { "value": "Dentratha" },
        { "value": "Doudra" },
        { "value": "Driindar" },
        { "value": "Eggren" },
        { "value": "Farideh" },
        { "value": "Findex" },
        { "value": "Furrele" },
        { "value": "Gesrethe" },
        { "value": "Gilkass" },
        { "value": "Harann" },
        { "value": "Havilar" },
        { "value": "Hethress" },
        { "value": "Hillanot" },
        { "value": "Jaxi" },
        { "value": "Jezean" },
        { "value": "Jheri" },
        { "value": "Kadana" },
        { "value": "Kava" },
        { "value": "Korinn" },
        { "value": "Megren" },
        { "value": "Mijira" },
        { "value": "Mishann" },
        { "value": "Nala" },
        { "value": "Nuthra" },
        { "value": "Perra" },
        { "value": "Pogranix" },
        { "value": "Pyxrin" },
        { "value": "Quespa" },
        { "value": "Raiann" },
        { "value": "Rezena" },
        { "value": "Ruloth" },
        { "value": "Saphara" },
        { "value": "Savaran" },
        { "value": "Sora" },
        { "value": "Surina" },
        { "value": "Synthrin" },
        { "value": "Tatyan" },
        { "value": "Thava" },
        { "value": "Uadjit" },
        { "value": "Vezera" },
        { "value": "Zykroff" }
      ]
    }, {
      "restrictions": {
        "gender": [ "male" ],
        "race": [ "dragonborn" ]
      },
      "entries": [
        { "value": "Adrex" },
        { "value": "Arjhan" },
        { "value": "Azzakh" },
        { "value": "Balasar" },
        { "value": "Baradad" },
        { "value": "Bharash" },
        { "value": "Bidreked" },
        { "value": "Dadalan" },
        { "value": "Dazzazn" },
        { "value": "Direcris" },
        { "value": "Donaar" },
        { "value": "Fax" },
        { "value": "Gargax" },
        { "value": "Ghesh" },
        { "value": "Gorbundus" },
        { "value": "Greethen" },
        { "value": "Heskan" },
        { "value": "Hirrathak" },
        { "value": "Ildrex" },
        { "value": "Kaladan" },
        { "value": "Kerkad" },
        { "value": "Kiirith" },
        { "value": "Kriv" },
        { "value": "Maagog" },
        { "value": "Medrash" },
        { "value": "Mehen" },
        { "value": "Mozikth" },
        { "value": "Mreksh" },
        { "value": "Mugrunden" },
        { "value": "Nadarr" },
        { "value": "Nithther" },
        { "value": "Norkruuth" },
        { "value": "Nykkan" },
        { "value": "Pandjed" },
        { "value": "Patrin" },
        { "value": "Piijink" },
        { "value": "Quarethon" },
        { "value": "Rathkran" },
        { "value": "Rhogar" },
        { "value": "Rivaan" },
        { "value": "Sethrekar" },
        { "value": "Shamash" },
        { "value": "Shedinn" },
        { "value": "Srorthen" },
        { "value": "Tarhun" },
        { "value": "Torinn" },
        { "value": "Trynnicus" },
        { "value": "Valorean" },
        { "value": "Vrondiss" },
        { "value": "Zedaar" }
      ]
    }],
    "lastName": [{
      "restrictions": {
        "race": [ "dragonborn" ]
      },
      "entries": [
        { "value": "Akambherylliax" },
        { "value": "Argenthrixus" },
        { "value": "Baharoosh" },
        { "value": "Beryntolthropal" },
        { "value": "Bhenkumbyrznaax" },
        { "value": "Caavylteradyn" },
        { "value": "Chumbyxirinnish" },
        { "value": "Clethtinthiallor" },
        { "value": "Daardendrian" },
        { "value": "Delmirev" },
        { "value": "Dhyrktelonis" },
        { "value": "Ebynichtomonis" },
        { "value": "Esstyrlynn" },
        { "value": "Fharngnarthnost" },
        { "value": "Ghaallixirn" },
        { "value": "Grrrmmballhyst" },
        { "value": "Gygazzylyshrift" },
        { "value": "Hashphronyxadyn" },
        { "value": "Hshhsstoroth" },
        { "value": "Imbixtellrhyst" },
        { "value": "Jerynomonis" },
        { "value": "Jharthraxyn" },
        { "value": "Kerrhylon" },
        { "value": "Kimbatuul" },
        { "value": "Lhamboldennish" },
        { "value": "Linxakasendalor" },
        { "value": "Mohradyllion" },
        { "value": "Mystan" },
        { "value": "Nemmonis" },
        { "value": "Norixius" },
        { "value": "Ophinshtalajiir" },
        { "value": "Orexijandilin" },
        { "value": "Pfaphnyrennish" },
        { "value": "Phrahdrandon" },
        { "value": "Pyraxtallinost" },
        { "value": "Qyxpahrgh" },
        { "value": "Raghthrknaar" },
        { "value": "Shestendeliath" },
        { "value": "Skaarzborroosh" },
        { "value": "Sumnarghthrysh" },
        { "value": "Tiammanthyllish" },
        { "value": "Turnuroth" },
        { "value": "Umbyrphrael" },
        { "value": "Vangdondalor" },
        { "value": "Verthisathurgiesh" },
        { "value": "Wivvyrholdalphiax" },
        { "value": "Wystongjiir" },
        { "value": "Xephyrbahnor" },
        { "value": "Yarjerit" },
        { "value": "Zzzxaaxthroth" }
      ]
    }]
  }
}
